<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />
    <PackageReference Include="Npgsql" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Persistence\SqlMigrations\*.sql" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SpaceForum.Application\SpaceForum.Application.csproj" />
    <ProjectReference Include="..\SpaceForum.Domain\SpaceForum.Domain.csproj" />
  </ItemGroup>

</Project>
