CREATE SCHEMA IF NOT EXISTS forums;
CREATE SCHEMA IF NOT EXISTS members;
CREATE SCHEMA IF NOT EXISTS discussions;
CREATE SCHEMA IF NOT EXISTS audit;
CREATE SCHEMA IF NOT EXISTS messaging;
CREATE SCHEMA IF NOT EXISTS configuration;

CREATE TABLE IF NOT EXISTS "AspNetRoles" (
    "Id" uuid PRIMARY KEY,
    "Name" varchar(256),
    "NormalizedName" varchar(256),
    "ConcurrencyStamp" text
);

CREATE TABLE IF NOT EXISTS "AspNetUsers" (
    "Id" uuid PRIMARY KEY,
    "UserName" varchar(256),
    "NormalizedUserName" varchar(256),
    "Email" varchar(256),
    "NormalizedEmail" varchar(256),
    "EmailConfirmed" boolean NOT NULL DEFAULT false,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" varchar(256),
    "PhoneNumberConfirmed" boolean NOT NULL DEFAULT false,
    "TwoFactorEnabled" boolean NOT NULL DEFAULT false,
    "LockoutEnd" timestamptz,
    "LockoutEnabled" boolean NOT NULL DEFAULT true,
    "AccessFailedCount" integer NOT NULL DEFAULT 0 CHECK ("AccessFailedCount" >= 0)
);

CREATE TABLE IF NOT EXISTS "AspNetRoleClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "RoleId" uuid NOT NULL REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
    "ClaimType" text,
    "ClaimValue" text
);

CREATE TABLE IF NOT EXISTS "AspNetUserClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId" uuid NOT NULL REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    "ClaimType" text,
    "ClaimValue" text
);

CREATE TABLE IF NOT EXISTS "AspNetUserLogins" (
    "LoginProvider" varchar(128) NOT NULL,
    "ProviderKey" varchar(128) NOT NULL,
    "ProviderDisplayName" text,
    "UserId" uuid NOT NULL REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    PRIMARY KEY ("LoginProvider", "ProviderKey")
);

CREATE TABLE IF NOT EXISTS "AspNetUserPasskeys" (
    "CredentialId" bytea PRIMARY KEY,
    "UserId" uuid NOT NULL REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    "Data" jsonb NOT NULL
);

CREATE TABLE IF NOT EXISTS "AspNetUserRoles" (
    "UserId" uuid NOT NULL REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    "RoleId" uuid NOT NULL REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
    PRIMARY KEY ("UserId", "RoleId")
);

CREATE TABLE IF NOT EXISTS "AspNetUserTokens" (
    "UserId" uuid NOT NULL REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    "LoginProvider" varchar(128) NOT NULL,
    "Name" varchar(128) NOT NULL,
    "Value" text,
    PRIMARY KEY ("UserId", "LoginProvider", "Name")
);

CREATE TABLE IF NOT EXISTS members.member_profiles (
    "Id" uuid PRIMARY KEY REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    "Login" varchar(30) NOT NULL CHECK ("Login" ~ '^[a-z0-9]{3,30}$'),
    "DisplayName" varchar(50) NOT NULL,
    "Biography" varchar(500),
    "Location" varchar(100),
    "Website" varchar(200),
    "AvatarUrl" varchar(500),
    "CreatedAt" timestamptz NOT NULL,
    "UpdatedAt" timestamptz NOT NULL,
    "Version" bigint NOT NULL CHECK ("Version" > 0)
);

CREATE TABLE IF NOT EXISTS forums.categories (
    "Id" uuid PRIMARY KEY,
    "Name" varchar(60) NOT NULL,
    "Slug" varchar(60) NOT NULL,
    "Description" varchar(240) NOT NULL,
    "Format" varchar(32) NOT NULL CHECK ("Format" IN ('Discussion', 'Q&A', 'Announcement')),
    "ParentId" uuid REFERENCES forums.categories ("Id") ON DELETE RESTRICT,
    "Position" integer NOT NULL CHECK ("Position" >= 0),
    "CreatedAt" timestamptz NOT NULL,
    "UpdatedAt" timestamptz NOT NULL,
    "Version" bigint NOT NULL CHECK ("Version" > 0)
);

CREATE TABLE IF NOT EXISTS discussions.topics (
    "Id" uuid PRIMARY KEY,
    "Number" bigint GENERATED BY DEFAULT AS IDENTITY,
    "CategoryId" uuid NOT NULL REFERENCES forums.categories ("Id") ON DELETE RESTRICT,
    "AuthorId" uuid NOT NULL REFERENCES members.member_profiles ("Id") ON DELETE RESTRICT,
    "Slug" varchar(180) NOT NULL,
    "Title" varchar(160) NOT NULL,
    "CreatedAt" timestamptz NOT NULL,
    "LastActivityAt" timestamptz NOT NULL,
    "ReplyCount" integer NOT NULL CHECK ("ReplyCount" >= 0),
    "IsClosed" boolean NOT NULL,
    "IsSticky" boolean NOT NULL DEFAULT false,
    "HiddenAt" timestamptz,
    "HiddenByMemberId" uuid REFERENCES members.member_profiles ("Id") ON DELETE SET NULL,
    "Version" bigint NOT NULL CHECK ("Version" > 0)
);

CREATE TABLE IF NOT EXISTS discussions.posts (
    "Id" uuid PRIMARY KEY,
    "TopicId" uuid NOT NULL REFERENCES discussions.topics ("Id") ON DELETE CASCADE,
    "AuthorId" uuid NOT NULL REFERENCES members.member_profiles ("Id") ON DELETE RESTRICT,
    "Number" integer NOT NULL CHECK ("Number" > 0),
    "Body" varchar(20000) NOT NULL,
    "ReplyToPostId" uuid REFERENCES discussions.posts ("Id") ON DELETE SET NULL,
    "CreatedAt" timestamptz NOT NULL,
    "UpdatedAt" timestamptz NOT NULL,
    "HiddenAt" timestamptz,
    "HiddenByMemberId" uuid REFERENCES members.member_profiles ("Id") ON DELETE SET NULL,
    "Version" bigint NOT NULL CHECK ("Version" > 0)
);

CREATE TABLE IF NOT EXISTS discussions.post_revisions (
    "Id" uuid PRIMARY KEY,
    "PostId" uuid NOT NULL REFERENCES discussions.posts ("Id") ON DELETE CASCADE,
    "EditorMemberId" uuid NOT NULL REFERENCES members.member_profiles ("Id") ON DELETE RESTRICT,
    "PreviousBody" varchar(20000) NOT NULL,
    "Body" varchar(20000) NOT NULL,
    "EditedAt" timestamptz NOT NULL
);

CREATE TABLE IF NOT EXISTS discussions.tags (
    "Id" uuid PRIMARY KEY,
    "Name" varchar(40) NOT NULL,
    "Slug" varchar(40) NOT NULL,
    "Description" varchar(160) NOT NULL,
    "Color" varchar(7) NOT NULL CHECK ("Color" ~ '^#[0-9a-fA-F]{6}$'),
    "Position" integer NOT NULL DEFAULT 0 CHECK ("Position" >= 0)
);

CREATE TABLE IF NOT EXISTS discussions.topic_tags (
    "TopicId" uuid NOT NULL REFERENCES discussions.topics ("Id") ON DELETE CASCADE,
    "TagId" uuid NOT NULL REFERENCES discussions.tags ("Id") ON DELETE CASCADE,
    PRIMARY KEY ("TopicId", "TagId")
);

CREATE TABLE IF NOT EXISTS discussions.topic_subscriptions (
    "TopicId" uuid NOT NULL REFERENCES discussions.topics ("Id") ON DELETE CASCADE,
    "MemberId" uuid NOT NULL REFERENCES members.member_profiles ("Id") ON DELETE CASCADE,
    "State" varchar(16) NOT NULL CHECK ("State" IN ('Following', 'Ignoring')),
    "LastReadPostNumber" integer NOT NULL DEFAULT 0 CHECK ("LastReadPostNumber" >= 0),
    "UpdatedAt" timestamptz NOT NULL,
    PRIMARY KEY ("TopicId", "MemberId")
);

CREATE TABLE IF NOT EXISTS discussions.notifications (
    "Id" uuid PRIMARY KEY,
    "RecipientMemberId" uuid NOT NULL REFERENCES members.member_profiles ("Id") ON DELETE CASCADE,
    "ActorMemberId" uuid REFERENCES members.member_profiles ("Id") ON DELETE SET NULL,
    "Type" varchar(40) NOT NULL,
    "TopicId" uuid REFERENCES discussions.topics ("Id") ON DELETE CASCADE,
    "PostId" uuid REFERENCES discussions.posts ("Id") ON DELETE CASCADE,
    "Data" jsonb NOT NULL DEFAULT '{}'::jsonb,
    "CreatedAt" timestamptz NOT NULL,
    "ReadAt" timestamptz
);

CREATE TABLE IF NOT EXISTS discussions.post_reactions (
    "PostId" uuid NOT NULL REFERENCES discussions.posts ("Id") ON DELETE CASCADE,
    "MemberId" uuid NOT NULL REFERENCES members.member_profiles ("Id") ON DELETE CASCADE,
    "Reaction" varchar(24) NOT NULL,
    "CreatedAt" timestamptz NOT NULL,
    PRIMARY KEY ("PostId", "MemberId", "Reaction")
);

CREATE TABLE IF NOT EXISTS discussions.post_reports (
    "Id" uuid PRIMARY KEY,
    "PostId" uuid NOT NULL REFERENCES discussions.posts ("Id") ON DELETE CASCADE,
    "ReporterMemberId" uuid NOT NULL REFERENCES members.member_profiles ("Id") ON DELETE CASCADE,
    "Reason" varchar(40) NOT NULL,
    "Details" varchar(1000),
    "Status" varchar(20) NOT NULL CHECK ("Status" IN ('Open', 'Resolved', 'Dismissed')),
    "AssignedMemberId" uuid REFERENCES members.member_profiles ("Id") ON DELETE SET NULL,
    "CreatedAt" timestamptz NOT NULL,
    "UpdatedAt" timestamptz NOT NULL,
    UNIQUE ("PostId", "ReporterMemberId")
);

CREATE TABLE IF NOT EXISTS discussions.post_bookmarks (
    "PostId" uuid NOT NULL REFERENCES discussions.posts ("Id") ON DELETE CASCADE,
    "MemberId" uuid NOT NULL REFERENCES members.member_profiles ("Id") ON DELETE CASCADE,
    "CreatedAt" timestamptz NOT NULL,
    PRIMARY KEY ("PostId", "MemberId")
);

CREATE TABLE IF NOT EXISTS discussions.attachments (
    "Id" uuid PRIMARY KEY,
    "PostId" uuid REFERENCES discussions.posts ("Id") ON DELETE CASCADE,
    "UploaderMemberId" uuid NOT NULL REFERENCES members.member_profiles ("Id") ON DELETE CASCADE,
    "OriginalFileName" varchar(255) NOT NULL,
    "StorageKey" varchar(255) NOT NULL,
    "ContentType" varchar(100) NOT NULL,
    "Size" bigint NOT NULL CHECK ("Size" > 0 AND "Size" <= 15728640),
    "CreatedAt" timestamptz NOT NULL
);

CREATE TABLE IF NOT EXISTS messaging.conversations (
    "Id" uuid PRIMARY KEY,
    "Subject" varchar(160) NOT NULL,
    "CreatedByMemberId" uuid NOT NULL REFERENCES members.member_profiles ("Id") ON DELETE RESTRICT,
    "CreatedAt" timestamptz NOT NULL,
    "LastMessageAt" timestamptz NOT NULL
);

CREATE TABLE IF NOT EXISTS messaging.conversation_members (
    "ConversationId" uuid NOT NULL REFERENCES messaging.conversations ("Id") ON DELETE CASCADE,
    "MemberId" uuid NOT NULL REFERENCES members.member_profiles ("Id") ON DELETE CASCADE,
    "JoinedAt" timestamptz NOT NULL,
    "LastReadAt" timestamptz,
    PRIMARY KEY ("ConversationId", "MemberId")
);

CREATE TABLE IF NOT EXISTS messaging.messages (
    "Id" uuid PRIMARY KEY,
    "ConversationId" uuid NOT NULL REFERENCES messaging.conversations ("Id") ON DELETE CASCADE,
    "AuthorMemberId" uuid NOT NULL REFERENCES members.member_profiles ("Id") ON DELETE RESTRICT,
    "Body" varchar(10000) NOT NULL,
    "CreatedAt" timestamptz NOT NULL,
    "EditedAt" timestamptz
);

CREATE TABLE IF NOT EXISTS configuration.forum_settings (
    "Key" varchar(100) PRIMARY KEY,
    "Value" jsonb NOT NULL,
    "UpdatedAt" timestamptz NOT NULL,
    "UpdatedByMemberId" uuid REFERENCES members.member_profiles ("Id") ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS discussions.topic_votes (
    "TopicId" uuid NOT NULL REFERENCES discussions.topics ("Id") ON DELETE CASCADE,
    "MemberId" uuid NOT NULL REFERENCES members.member_profiles ("Id") ON DELETE CASCADE,
    "Value" smallint NOT NULL CHECK ("Value" IN (-1, 1)),
    "CreatedAt" timestamptz NOT NULL,
    "UpdatedAt" timestamptz NOT NULL,
    PRIMARY KEY ("TopicId", "MemberId")
);

CREATE TABLE IF NOT EXISTS audit.security_audit_events (
    "Id" uuid PRIMARY KEY,
    "OccurredAt" timestamptz NOT NULL,
    "EventType" varchar(100) NOT NULL,
    "ActorMemberId" uuid,
    "SubjectId" varchar(100),
    "Succeeded" boolean NOT NULL
);

CREATE INDEX IF NOT EXISTS "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");
CREATE UNIQUE INDEX IF NOT EXISTS "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");
CREATE INDEX IF NOT EXISTS "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");
CREATE INDEX IF NOT EXISTS "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");
CREATE INDEX IF NOT EXISTS "IX_AspNetUserPasskeys_UserId" ON "AspNetUserPasskeys" ("UserId");
CREATE INDEX IF NOT EXISTS "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");
DROP INDEX IF EXISTS "EmailIndex";
CREATE UNIQUE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail") WHERE "NormalizedEmail" IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");
CREATE INDEX IF NOT EXISTS "IX_categories_ParentId_Position" ON forums.categories ("ParentId", "Position");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_categories_Slug" ON forums.categories ("Slug");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_member_profiles_Login" ON members.member_profiles ("Login");
CREATE INDEX IF NOT EXISTS "IX_posts_AuthorId" ON discussions.posts ("AuthorId");
CREATE INDEX IF NOT EXISTS "IX_posts_ReplyToPostId" ON discussions.posts ("ReplyToPostId");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_posts_TopicId_Number" ON discussions.posts ("TopicId", "Number");
CREATE INDEX IF NOT EXISTS "IX_security_audit_events_EventType_OccurredAt" ON audit.security_audit_events ("EventType", "OccurredAt");
CREATE INDEX IF NOT EXISTS "IX_security_audit_events_OccurredAt" ON audit.security_audit_events ("OccurredAt");
CREATE INDEX IF NOT EXISTS "IX_topics_AuthorId" ON discussions.topics ("AuthorId");
CREATE INDEX IF NOT EXISTS "IX_topics_CategoryId_LastActivityAt" ON discussions.topics ("CategoryId", "LastActivityAt" DESC);
CREATE INDEX IF NOT EXISTS "IX_topics_LastActivityAt" ON discussions.topics ("LastActivityAt" DESC);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_topics_Number" ON discussions.topics ("Number");
CREATE INDEX IF NOT EXISTS "IX_topics_Title_Search" ON discussions.topics USING gin (to_tsvector('simple', "Title"));
CREATE INDEX IF NOT EXISTS "IX_posts_Body_Search" ON discussions.posts USING gin (to_tsvector('simple', "Body"));
CREATE INDEX IF NOT EXISTS "IX_topic_votes_MemberId" ON discussions.topic_votes ("MemberId");
CREATE INDEX IF NOT EXISTS "IX_post_revisions_PostId_EditedAt" ON discussions.post_revisions ("PostId", "EditedAt" DESC);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_tags_Slug" ON discussions.tags ("Slug");
CREATE INDEX IF NOT EXISTS "IX_topic_tags_TagId" ON discussions.topic_tags ("TagId");
CREATE INDEX IF NOT EXISTS "IX_topic_subscriptions_MemberId_UpdatedAt" ON discussions.topic_subscriptions ("MemberId", "UpdatedAt" DESC);
CREATE INDEX IF NOT EXISTS "IX_notifications_Recipient_Read_Created" ON discussions.notifications ("RecipientMemberId", "ReadAt", "CreatedAt" DESC);
CREATE INDEX IF NOT EXISTS "IX_post_reactions_MemberId" ON discussions.post_reactions ("MemberId");
CREATE INDEX IF NOT EXISTS "IX_post_reports_Status_CreatedAt" ON discussions.post_reports ("Status", "CreatedAt");
CREATE INDEX IF NOT EXISTS "IX_post_bookmarks_MemberId_CreatedAt" ON discussions.post_bookmarks ("MemberId", "CreatedAt" DESC);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_attachments_StorageKey" ON discussions.attachments ("StorageKey");
CREATE INDEX IF NOT EXISTS "IX_conversation_members_MemberId" ON messaging.conversation_members ("MemberId");
CREATE INDEX IF NOT EXISTS "IX_messages_ConversationId_CreatedAt" ON messaging.messages ("ConversationId", "CreatedAt");
