using Npgsql;
using SpaceForum.Application.Messaging;

namespace SpaceForum.Infrastructure.Persistence;

public sealed class MessagingRepository(NpgsqlDataSource dataSource):IMessagingRepository
{
    public async Task<IReadOnlyList<ConversationView>> ListAsync(Guid memberId,CancellationToken cancellationToken){await using var command=dataSource.CreateCommand("SELECT conversation.\"Id\",conversation.\"Subject\",conversation.\"LastMessageAt\",string_agg(profile.\"DisplayName\",', ' ORDER BY profile.\"DisplayName\"),COUNT(*) FILTER (WHERE message.\"CreatedAt\">COALESCE(own.\"LastReadAt\",'-infinity'))::int FROM messaging.conversations AS conversation INNER JOIN messaging.conversation_members AS own ON own.\"ConversationId\"=conversation.\"Id\" AND own.\"MemberId\"=@memberId INNER JOIN messaging.conversation_members AS participant ON participant.\"ConversationId\"=conversation.\"Id\" INNER JOIN members.member_profiles AS profile ON profile.\"Id\"=participant.\"MemberId\" LEFT JOIN messaging.messages AS message ON message.\"ConversationId\"=conversation.\"Id\" AND message.\"AuthorMemberId\"<>@memberId GROUP BY conversation.\"Id\",own.\"LastReadAt\" ORDER BY conversation.\"LastMessageAt\" DESC;");command.Parameters.AddWithValue("memberId",memberId);var items=new List<ConversationView>();await using var reader=await command.ExecuteReaderAsync(cancellationToken);while(await reader.ReadAsync(cancellationToken))items.Add(new(reader.GetGuid(0),reader.GetString(1),reader.GetFieldValue<DateTimeOffset>(2),reader.GetString(3),reader.GetInt32(4)));return items;}
    public async Task<ConversationDetailView?> GetAsync(Guid conversationId,Guid memberId,CancellationToken cancellationToken){await using var connection=await dataSource.OpenConnectionAsync(cancellationToken);string? subject;await using(var access=connection.CreateCommand()){access.CommandText="UPDATE messaging.conversation_members SET \"LastReadAt\"=now() WHERE \"ConversationId\"=@id AND \"MemberId\"=@memberId RETURNING (SELECT \"Subject\" FROM messaging.conversations WHERE \"Id\"=@id);";access.Parameters.AddWithValue("id",conversationId);access.Parameters.AddWithValue("memberId",memberId);subject=(string?)await access.ExecuteScalarAsync(cancellationToken);}if(subject is null)return null;var messages=new List<MessageView>();await using(var command=connection.CreateCommand()){command.CommandText="SELECT message.\"Id\",profile.\"Login\",profile.\"DisplayName\",message.\"Body\",message.\"CreatedAt\" FROM messaging.messages AS message INNER JOIN members.member_profiles AS profile ON profile.\"Id\"=message.\"AuthorMemberId\" WHERE message.\"ConversationId\"=@id ORDER BY message.\"CreatedAt\";";command.Parameters.AddWithValue("id",conversationId);await using var reader=await command.ExecuteReaderAsync(cancellationToken);while(await reader.ReadAsync(cancellationToken))messages.Add(new(reader.GetGuid(0),reader.GetString(1),reader.GetString(2),reader.GetString(3),reader.GetFieldValue<DateTimeOffset>(4)));}return new(conversationId,subject,messages);}
    public async Task<Guid?> CreateAsync(Guid creatorId,Guid recipientId,string subject,string body,DateTimeOffset createdAt,CancellationToken cancellationToken){await using var connection=await dataSource.OpenConnectionAsync(cancellationToken);await using var transaction=await connection.BeginTransactionAsync(cancellationToken);var id=Guid.CreateVersion7(createdAt);await using(var command=connection.CreateCommand()){command.Transaction=transaction;command.CommandText="INSERT INTO messaging.conversations (\"Id\",\"Subject\",\"CreatedByMemberId\",\"CreatedAt\",\"LastMessageAt\") SELECT @id,@subject,@creator,@at,@at WHERE EXISTS(SELECT 1 FROM members.member_profiles WHERE \"Id\"=@recipient);";command.Parameters.AddWithValue("id",id);command.Parameters.AddWithValue("subject",subject);command.Parameters.AddWithValue("creator",creatorId);command.Parameters.AddWithValue("recipient",recipientId);command.Parameters.AddWithValue("at",createdAt);if(await command.ExecuteNonQueryAsync(cancellationToken)!=1)return null;}foreach(var member in new[]{creatorId,recipientId}.Distinct()){await using var command=connection.CreateCommand();command.Transaction=transaction;command.CommandText="INSERT INTO messaging.conversation_members (\"ConversationId\",\"MemberId\",\"JoinedAt\",\"LastReadAt\") VALUES (@id,@member,@at,@readAt);";command.Parameters.AddWithValue("id",id);command.Parameters.AddWithValue("member",member);command.Parameters.AddWithValue("at",createdAt);command.Parameters.AddWithValue("readAt",member==creatorId?createdAt:DBNull.Value);await command.ExecuteNonQueryAsync(cancellationToken);}await InsertMessageAsync(connection,transaction,id,creatorId,body,createdAt,cancellationToken);await transaction.CommitAsync(cancellationToken);return id;}
    public async Task<bool> SendAsync(Guid conversationId,Guid authorId,string body,DateTimeOffset createdAt,CancellationToken cancellationToken){await using var connection=await dataSource.OpenConnectionAsync(cancellationToken);await using var transaction=await connection.BeginTransactionAsync(cancellationToken);await using(var access=connection.CreateCommand()){access.Transaction=transaction;access.CommandText="UPDATE messaging.conversations SET \"LastMessageAt\"=@at WHERE \"Id\"=@id AND EXISTS(SELECT 1 FROM messaging.conversation_members WHERE \"ConversationId\"=@id AND \"MemberId\"=@author);";access.Parameters.AddWithValue("id",conversationId);access.Parameters.AddWithValue("author",authorId);access.Parameters.AddWithValue("at",createdAt);if(await access.ExecuteNonQueryAsync(cancellationToken)!=1)return false;}await InsertMessageAsync(connection,transaction,conversationId,authorId,body,createdAt,cancellationToken);await transaction.CommitAsync(cancellationToken);return true;}
    private static async Task InsertMessageAsync(NpgsqlConnection connection,NpgsqlTransaction transaction,Guid id,Guid author,string body,DateTimeOffset at,CancellationToken cancellationToken){await using var command=connection.CreateCommand();command.Transaction=transaction;command.CommandText="INSERT INTO messaging.messages (\"Id\",\"ConversationId\",\"AuthorMemberId\",\"Body\",\"CreatedAt\") VALUES (@messageId,@id,@author,@body,@at);";command.Parameters.AddWithValue("messageId",Guid.CreateVersion7(at));command.Parameters.AddWithValue("id",id);command.Parameters.AddWithValue("author",author);command.Parameters.AddWithValue("body",body);command.Parameters.AddWithValue("at",at);await command.ExecuteNonQueryAsync(cancellationToken);}
}
